import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by Next.js",
};

export default function Page() {
  return (
    <>
      <h1>Hello next JS</h1>
      <Link href="/dashboard">To dashboard</Link>
      <br />
      <Link href="/dashboard/settings">To settings</Link>
    </>
  );
}
